#app
server:
    port: 8080


spring:
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    url: jdbc:mysql://47.99.216.57:3306/share_self?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
#  mapper-locations: classpath:/mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.baomidou.springboot.content.entity,com.baomidou.springboot.auth.entity,com.baomidou.springboot.im.entity
  typeEnumsPackage: com.baomidou.springboot.content.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springbootgboot      #自定义SQL注入器
      #sql-injector: com.baomidou.springbootgboot  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging


#上传文件的路径
share.file.storage.path: F:/imgAndVideo/all

